spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  session:
    store-type: jdbc

server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: studybuddy
    key-password: ${KEYSTORE_PASSWORD}


servlet:
  session:
    cookie:
      http-only: true
      secure: false
      same-site: None
      name: JSESSIONID

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"

