spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Va actualiza tabelele existente, adăugând câmpuri noi dacă e nevoie
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: true
      hibernate.format_sql: true  # Acesta va formata SQL-ul pentru a fi mai ușor de citit

server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: studybuddy
    key-password: ${KEYSTORE_PASSWORD}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
